/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

import java.util.Date;

public class ActivityObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.projectId
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.companyId
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.subject
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.target
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.content
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.creatorId
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.action
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.attachId
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    private Integer attachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.attachType
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    private String attachType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.created
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.creatorName
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.projectName
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    private String creatorAvatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.trash
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    private Boolean trash;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.id
     *
     * @param id the value for activity.id
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.projectId
     *
     * @return the value of activity.projectId
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.projectId
     *
     * @param projectId the value for activity.projectId
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.companyId
     *
     * @return the value of activity.companyId
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.companyId
     *
     * @param companyId the value for activity.companyId
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.subject
     *
     * @return the value of activity.subject
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.subject
     *
     * @param subject the value for activity.subject
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.target
     *
     * @return the value of activity.target
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.target
     *
     * @param target the value for activity.target
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.content
     *
     * @return the value of activity.content
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.content
     *
     * @param content the value for activity.content
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.creatorId
     *
     * @return the value of activity.creatorId
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.creatorId
     *
     * @param creatorId the value for activity.creatorId
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.action
     *
     * @return the value of activity.action
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.action
     *
     * @param action the value for activity.action
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.attachId
     *
     * @return the value of activity.attachId
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public Integer getAttachId() {
        return attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.attachId
     *
     * @param attachId the value for activity.attachId
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public void setAttachId(Integer attachId) {
        this.attachId = attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.attachType
     *
     * @return the value of activity.attachType
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public String getAttachType() {
        return attachType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.attachType
     *
     * @param attachType the value for activity.attachType
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public void setAttachType(String attachType) {
        this.attachType = attachType == null ? null : attachType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.created
     *
     * @return the value of activity.created
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.created
     *
     * @param created the value for activity.created
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.creatorName
     *
     * @return the value of activity.creatorName
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.creatorName
     *
     * @param creatorName the value for activity.creatorName
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.projectName
     *
     * @return the value of activity.projectName
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.projectName
     *
     * @param projectName the value for activity.projectName
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.creatorAvatar
     *
     * @return the value of activity.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public String getCreatorAvatar() {
        return creatorAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.creatorAvatar
     *
     * @param creatorAvatar the value for activity.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public void setCreatorAvatar(String creatorAvatar) {
        this.creatorAvatar = creatorAvatar == null ? null : creatorAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.trash
     *
     * @return the value of activity.trash
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public Boolean getTrash() {
        return trash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.trash
     *
     * @param trash the value for activity.trash
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public void setTrash(Boolean trash) {
        this.trash = trash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public ActivityObject(ActivityObject parent) {
        this.id = parent.getId();
        this.projectId = parent.getProjectId();
        this.companyId = parent.getCompanyId();
        this.subject = parent.getSubject();
        this.target = parent.getTarget();
        this.content = parent.getContent();
        this.creatorId = parent.getCreatorId();
        this.action = parent.getAction();
        this.attachId = parent.getAttachId();
        this.attachType = parent.getAttachType();
        this.created = parent.getCreated();
        this.creatorName = parent.getCreatorName();
        this.projectName = parent.getProjectName();
        this.creatorAvatar = parent.getCreatorAvatar();
        this.trash = parent.getTrash();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public ActivityObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Aug 26 20:27:42 CST 2015
     */
    public ActivityObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Wed Aug 26 20:27:43 CST 2015
     */
    @Override
    public ActivityObject copy() {
        return new ActivityObject(this);
    }
}