/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

public class AttachTodoObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attach_todo.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attach_todo.attachType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String attachType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attach_todo.attachId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer attachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attach_todo.todoId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer todoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attach_todo.id
     *
     * @return the value of attach_todo.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attach_todo.id
     *
     * @param id the value for attach_todo.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attach_todo.attachType
     *
     * @return the value of attach_todo.attachType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getAttachType() {
        return attachType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attach_todo.attachType
     *
     * @param attachType the value for attach_todo.attachType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setAttachType(String attachType) {
        this.attachType = attachType == null ? null : attachType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attach_todo.attachId
     *
     * @return the value of attach_todo.attachId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getAttachId() {
        return attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attach_todo.attachId
     *
     * @param attachId the value for attach_todo.attachId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setAttachId(Integer attachId) {
        this.attachId = attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attach_todo.todoId
     *
     * @return the value of attach_todo.todoId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getTodoId() {
        return todoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attach_todo.todoId
     *
     * @param todoId the value for attach_todo.todoId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setTodoId(Integer todoId) {
        this.todoId = todoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attach_todo
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public AttachTodoObject(AttachTodoObject parent) {
        this.id = parent.getId();
        this.attachType = parent.getAttachType();
        this.attachId = parent.getAttachId();
        this.todoId = parent.getTodoId();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attach_todo
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public AttachTodoObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attach_todo
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public AttachTodoObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attach_todo
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    @Override
    public AttachTodoObject copy() {
        return new AttachTodoObject(this);
    }
}