/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

public class CollectionObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.projectName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.creatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.creatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.attachId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer attachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.title
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.attachType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String attachType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String creatorAvatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.id
     *
     * @return the value of collection.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.id
     *
     * @param id the value for collection.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.userId
     *
     * @return the value of collection.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.userId
     *
     * @param userId the value for collection.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.companyId
     *
     * @return the value of collection.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.companyId
     *
     * @param companyId the value for collection.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.projectName
     *
     * @return the value of collection.projectName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.projectName
     *
     * @param projectName the value for collection.projectName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.projectId
     *
     * @return the value of collection.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.projectId
     *
     * @param projectId the value for collection.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.creatorId
     *
     * @return the value of collection.creatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.creatorId
     *
     * @param creatorId the value for collection.creatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.creatorName
     *
     * @return the value of collection.creatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.creatorName
     *
     * @param creatorName the value for collection.creatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.attachId
     *
     * @return the value of collection.attachId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getAttachId() {
        return attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.attachId
     *
     * @param attachId the value for collection.attachId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setAttachId(Integer attachId) {
        this.attachId = attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.deleted
     *
     * @return the value of collection.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.deleted
     *
     * @param deleted the value for collection.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.title
     *
     * @return the value of collection.title
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.title
     *
     * @param title the value for collection.title
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.attachType
     *
     * @return the value of collection.attachType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getAttachType() {
        return attachType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.attachType
     *
     * @param attachType the value for collection.attachType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setAttachType(String attachType) {
        this.attachType = attachType == null ? null : attachType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.creatorAvatar
     *
     * @return the value of collection.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getCreatorAvatar() {
        return creatorAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.creatorAvatar
     *
     * @param creatorAvatar the value for collection.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreatorAvatar(String creatorAvatar) {
        this.creatorAvatar = creatorAvatar == null ? null : creatorAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public CollectionObject(CollectionObject parent) {
        this.id = parent.getId();
        this.userId = parent.getUserId();
        this.companyId = parent.getCompanyId();
        this.projectName = parent.getProjectName();
        this.projectId = parent.getProjectId();
        this.creatorId = parent.getCreatorId();
        this.creatorName = parent.getCreatorName();
        this.attachId = parent.getAttachId();
        this.deleted = parent.getDeleted();
        this.title = parent.getTitle();
        this.attachType = parent.getAttachType();
        this.creatorAvatar = parent.getCreatorAvatar();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public CollectionObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public CollectionObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public CollectionObject(boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public CollectionObject(int id, boolean deleted) {
        this.id = id;
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    @Override
    public CollectionObject copy() {
        return new CollectionObject(this);
    }
}