/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

public class CompanyPrivilegeObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_privilege.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_privilege.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_privilege.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_privilege.isAdmin
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean isAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_privilege.canCreateProject
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean canCreateProject;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_privilege.id
     *
     * @return the value of company_privilege.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_privilege.id
     *
     * @param id the value for company_privilege.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_privilege.userId
     *
     * @return the value of company_privilege.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_privilege.userId
     *
     * @param userId the value for company_privilege.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_privilege.companyId
     *
     * @return the value of company_privilege.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_privilege.companyId
     *
     * @param companyId the value for company_privilege.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_privilege.isAdmin
     *
     * @return the value of company_privilege.isAdmin
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_privilege.isAdmin
     *
     * @param isAdmin the value for company_privilege.isAdmin
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_privilege.canCreateProject
     *
     * @return the value of company_privilege.canCreateProject
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getCanCreateProject() {
        return canCreateProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_privilege.canCreateProject
     *
     * @param canCreateProject the value for company_privilege.canCreateProject
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCanCreateProject(Boolean canCreateProject) {
        this.canCreateProject = canCreateProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_privilege
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public CompanyPrivilegeObject(CompanyPrivilegeObject parent) {
        this.id = parent.getId();
        this.userId = parent.getUserId();
        this.companyId = parent.getCompanyId();
        this.isAdmin = parent.getIsAdmin();
        this.canCreateProject = parent.getCanCreateProject();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_privilege
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public CompanyPrivilegeObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_privilege
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public CompanyPrivilegeObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_privilege
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    @Override
    public CompanyPrivilegeObject copy() {
        return new CompanyPrivilegeObject(this);
    }
}