/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

import java.util.Date;

public class HelpTipObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_tip.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_tip.title
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_tip.question
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_tip.answer
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_tip.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_tip.updated
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_tip.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_tip.id
     *
     * @return the value of help_tip.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_tip.id
     *
     * @param id the value for help_tip.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_tip.title
     *
     * @return the value of help_tip.title
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_tip.title
     *
     * @param title the value for help_tip.title
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_tip.question
     *
     * @return the value of help_tip.question
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_tip.question
     *
     * @param question the value for help_tip.question
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_tip.answer
     *
     * @return the value of help_tip.answer
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_tip.answer
     *
     * @param answer the value for help_tip.answer
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_tip.created
     *
     * @return the value of help_tip.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_tip.created
     *
     * @param created the value for help_tip.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_tip.updated
     *
     * @return the value of help_tip.updated
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_tip.updated
     *
     * @param updated the value for help_tip.updated
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_tip.deleted
     *
     * @return the value of help_tip.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_tip.deleted
     *
     * @param deleted the value for help_tip.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_tip
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public HelpTipObject(HelpTipObject parent) {
        this.id = parent.getId();
        this.title = parent.getTitle();
        this.question = parent.getQuestion();
        this.answer = parent.getAnswer();
        this.created = parent.getCreated();
        this.updated = parent.getUpdated();
        this.deleted = parent.getDeleted();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_tip
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public HelpTipObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_tip
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public HelpTipObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_tip
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public HelpTipObject(boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_tip
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public HelpTipObject(int id, boolean deleted) {
        this.id = id;
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_tip
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    @Override
    public HelpTipObject copy() {
        return new HelpTipObject(this);
    }
}