/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

import java.util.Date;

public class IterationAttachObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iteration_object.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iteration_object.iterationId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer iterationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iteration_object.objectType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String objectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iteration_object.objectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer objectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iteration_object.completed
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean completed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iteration_object.completedTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date completedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iteration_object.id
     *
     * @return the value of iteration_object.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iteration_object.id
     *
     * @param id the value for iteration_object.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iteration_object.iterationId
     *
     * @return the value of iteration_object.iterationId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getIterationId() {
        return iterationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iteration_object.iterationId
     *
     * @param iterationId the value for iteration_object.iterationId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setIterationId(Integer iterationId) {
        this.iterationId = iterationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iteration_object.objectType
     *
     * @return the value of iteration_object.objectType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iteration_object.objectType
     *
     * @param objectType the value for iteration_object.objectType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setObjectType(String objectType) {
        this.objectType = objectType == null ? null : objectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iteration_object.objectId
     *
     * @return the value of iteration_object.objectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iteration_object.objectId
     *
     * @param objectId the value for iteration_object.objectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setObjectId(Integer objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iteration_object.completed
     *
     * @return the value of iteration_object.completed
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getCompleted() {
        return completed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iteration_object.completed
     *
     * @param completed the value for iteration_object.completed
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompleted(Boolean completed) {
        this.completed = completed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iteration_object.completedTime
     *
     * @return the value of iteration_object.completedTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getCompletedTime() {
        return completedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iteration_object.completedTime
     *
     * @param completedTime the value for iteration_object.completedTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompletedTime(Date completedTime) {
        this.completedTime = completedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iteration_object
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public IterationAttachObject(IterationAttachObject parent) {
        this.id = parent.getId();
        this.iterationId = parent.getIterationId();
        this.objectType = parent.getObjectType();
        this.objectId = parent.getObjectId();
        this.completed = parent.getCompleted();
        this.completedTime = parent.getCompletedTime();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iteration_object
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public IterationAttachObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iteration_object
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public IterationAttachObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iteration_object
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    @Override
    public IterationAttachObject copy() {
        return new IterationAttachObject(this);
    }
}