/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

public class KeywordObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword.keyword
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword.times
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Long times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword.attachType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String attachType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword.attachId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer attachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyword.tfidf
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Double tfidf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword.id
     *
     * @return the value of keyword.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword.id
     *
     * @param id the value for keyword.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword.projectId
     *
     * @return the value of keyword.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword.projectId
     *
     * @param projectId the value for keyword.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword.companyId
     *
     * @return the value of keyword.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword.companyId
     *
     * @param companyId the value for keyword.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword.keyword
     *
     * @return the value of keyword.keyword
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword.keyword
     *
     * @param keyword the value for keyword.keyword
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword.times
     *
     * @return the value of keyword.times
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Long getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword.times
     *
     * @param times the value for keyword.times
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setTimes(Long times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword.attachType
     *
     * @return the value of keyword.attachType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getAttachType() {
        return attachType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword.attachType
     *
     * @param attachType the value for keyword.attachType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setAttachType(String attachType) {
        this.attachType = attachType == null ? null : attachType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword.attachId
     *
     * @return the value of keyword.attachId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getAttachId() {
        return attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword.attachId
     *
     * @param attachId the value for keyword.attachId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setAttachId(Integer attachId) {
        this.attachId = attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword.deleted
     *
     * @return the value of keyword.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword.deleted
     *
     * @param deleted the value for keyword.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyword.tfidf
     *
     * @return the value of keyword.tfidf
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Double getTfidf() {
        return tfidf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyword.tfidf
     *
     * @param tfidf the value for keyword.tfidf
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setTfidf(Double tfidf) {
        this.tfidf = tfidf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public KeywordObject(KeywordObject parent) {
        this.id = parent.getId();
        this.projectId = parent.getProjectId();
        this.companyId = parent.getCompanyId();
        this.keyword = parent.getKeyword();
        this.times = parent.getTimes();
        this.attachType = parent.getAttachType();
        this.attachId = parent.getAttachId();
        this.deleted = parent.getDeleted();
        this.tfidf = parent.getTfidf();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public KeywordObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public KeywordObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public KeywordObject(boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public KeywordObject(int id, boolean deleted) {
        this.id = id;
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    @Override
    public KeywordObject copy() {
        return new KeywordObject(this);
    }
}