/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

import java.util.Date;

public class NotificationObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.isRead
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.activityId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.id
     *
     * @return the value of notification.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.id
     *
     * @param id the value for notification.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.userId
     *
     * @return the value of notification.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.userId
     *
     * @param userId the value for notification.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.isRead
     *
     * @return the value of notification.isRead
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.isRead
     *
     * @param isRead the value for notification.isRead
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.activityId
     *
     * @return the value of notification.activityId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.activityId
     *
     * @param activityId the value for notification.activityId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.companyId
     *
     * @return the value of notification.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.companyId
     *
     * @param companyId the value for notification.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.created
     *
     * @return the value of notification.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.created
     *
     * @param created the value for notification.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public NotificationObject(NotificationObject parent) {
        this.id = parent.getId();
        this.userId = parent.getUserId();
        this.isRead = parent.getIsRead();
        this.activityId = parent.getActivityId();
        this.companyId = parent.getCompanyId();
        this.created = parent.getCreated();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public NotificationObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public NotificationObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    @Override
    public NotificationObject copy() {
        return new NotificationObject(this);
    }
}