/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

public class ProjectPrivilegeObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_privilege.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_privilege.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_privilege.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_privilege.isAdmin
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean isAdmin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_privilege.id
     *
     * @return the value of project_privilege.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_privilege.id
     *
     * @param id the value for project_privilege.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_privilege.userId
     *
     * @return the value of project_privilege.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_privilege.userId
     *
     * @param userId the value for project_privilege.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_privilege.projectId
     *
     * @return the value of project_privilege.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_privilege.projectId
     *
     * @param projectId the value for project_privilege.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_privilege.isAdmin
     *
     * @return the value of project_privilege.isAdmin
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_privilege.isAdmin
     *
     * @param isAdmin the value for project_privilege.isAdmin
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_privilege
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public ProjectPrivilegeObject(ProjectPrivilegeObject parent) {
        this.id = parent.getId();
        this.userId = parent.getUserId();
        this.projectId = parent.getProjectId();
        this.isAdmin = parent.getIsAdmin();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_privilege
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public ProjectPrivilegeObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_privilege
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public ProjectPrivilegeObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_privilege
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    @Override
    public ProjectPrivilegeObject copy() {
        return new ProjectPrivilegeObject(this);
    }
}