/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

import java.util.Date;

public class StepObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.attachType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String attachType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.attachId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer attachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.content
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.dueDate
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date dueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.createdTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.updatedTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.creatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.creatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.assigneeId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer assigneeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.status
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.startTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.completedTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date completedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.completerId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer completerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.idInProject
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer idInProject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String creatorAvatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.id
     *
     * @return the value of step.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.id
     *
     * @param id the value for step.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.attachType
     *
     * @return the value of step.attachType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getAttachType() {
        return attachType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.attachType
     *
     * @param attachType the value for step.attachType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setAttachType(String attachType) {
        this.attachType = attachType == null ? null : attachType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.attachId
     *
     * @return the value of step.attachId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getAttachId() {
        return attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.attachId
     *
     * @param attachId the value for step.attachId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setAttachId(Integer attachId) {
        this.attachId = attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.content
     *
     * @return the value of step.content
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.content
     *
     * @param content the value for step.content
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.dueDate
     *
     * @return the value of step.dueDate
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.dueDate
     *
     * @param dueDate the value for step.dueDate
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.createdTime
     *
     * @return the value of step.createdTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.createdTime
     *
     * @param createdTime the value for step.createdTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.updatedTime
     *
     * @return the value of step.updatedTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.updatedTime
     *
     * @param updatedTime the value for step.updatedTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.creatorId
     *
     * @return the value of step.creatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.creatorId
     *
     * @param creatorId the value for step.creatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.creatorName
     *
     * @return the value of step.creatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.creatorName
     *
     * @param creatorName the value for step.creatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.assigneeId
     *
     * @return the value of step.assigneeId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getAssigneeId() {
        return assigneeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.assigneeId
     *
     * @param assigneeId the value for step.assigneeId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setAssigneeId(Integer assigneeId) {
        this.assigneeId = assigneeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.status
     *
     * @return the value of step.status
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.status
     *
     * @param status the value for step.status
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.startTime
     *
     * @return the value of step.startTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.startTime
     *
     * @param startTime the value for step.startTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.completedTime
     *
     * @return the value of step.completedTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getCompletedTime() {
        return completedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.completedTime
     *
     * @param completedTime the value for step.completedTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompletedTime(Date completedTime) {
        this.completedTime = completedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.completerId
     *
     * @return the value of step.completerId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCompleterId() {
        return completerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.completerId
     *
     * @param completerId the value for step.completerId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompleterId(Integer completerId) {
        this.completerId = completerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.idInProject
     *
     * @return the value of step.idInProject
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getIdInProject() {
        return idInProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.idInProject
     *
     * @param idInProject the value for step.idInProject
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setIdInProject(Integer idInProject) {
        this.idInProject = idInProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.projectId
     *
     * @return the value of step.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.projectId
     *
     * @param projectId the value for step.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.companyId
     *
     * @return the value of step.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.companyId
     *
     * @param companyId the value for step.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.deleted
     *
     * @return the value of step.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.deleted
     *
     * @param deleted the value for step.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.creatorAvatar
     *
     * @return the value of step.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getCreatorAvatar() {
        return creatorAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.creatorAvatar
     *
     * @param creatorAvatar the value for step.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreatorAvatar(String creatorAvatar) {
        this.creatorAvatar = creatorAvatar == null ? null : creatorAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table step
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public StepObject(StepObject parent) {
        this.id = parent.getId();
        this.attachType = parent.getAttachType();
        this.attachId = parent.getAttachId();
        this.content = parent.getContent();
        this.dueDate = parent.getDueDate();
        this.createdTime = parent.getCreatedTime();
        this.updatedTime = parent.getUpdatedTime();
        this.creatorId = parent.getCreatorId();
        this.creatorName = parent.getCreatorName();
        this.assigneeId = parent.getAssigneeId();
        this.status = parent.getStatus();
        this.startTime = parent.getStartTime();
        this.completedTime = parent.getCompletedTime();
        this.completerId = parent.getCompleterId();
        this.idInProject = parent.getIdInProject();
        this.projectId = parent.getProjectId();
        this.companyId = parent.getCompanyId();
        this.deleted = parent.getDeleted();
        this.creatorAvatar = parent.getCreatorAvatar();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table step
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public StepObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table step
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public StepObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table step
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public StepObject(boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table step
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public StepObject(int id, boolean deleted) {
        this.id = id;
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table step
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    @Override
    public StepObject copy() {
        return new StepObject(this);
    }
}