/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

import java.util.Date;

public class StoryObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.pre
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String pre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.post
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.updated
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.completedTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date completedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.completed
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean completed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.creatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.creatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.description
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.acceptanceLevel
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String acceptanceLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.priority
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.parentStoryId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer parentStoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.completable
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean completable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String creatorAvatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.id
     *
     * @return the value of story.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.id
     *
     * @param id the value for story.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.projectId
     *
     * @return the value of story.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.projectId
     *
     * @param projectId the value for story.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.companyId
     *
     * @return the value of story.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.companyId
     *
     * @param companyId the value for story.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.pre
     *
     * @return the value of story.pre
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getPre() {
        return pre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.pre
     *
     * @param pre the value for story.pre
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setPre(String pre) {
        this.pre = pre == null ? null : pre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.post
     *
     * @return the value of story.post
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.post
     *
     * @param post the value for story.post
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.deleted
     *
     * @return the value of story.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.deleted
     *
     * @param deleted the value for story.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.created
     *
     * @return the value of story.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.created
     *
     * @param created the value for story.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.updated
     *
     * @return the value of story.updated
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.updated
     *
     * @param updated the value for story.updated
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.completedTime
     *
     * @return the value of story.completedTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getCompletedTime() {
        return completedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.completedTime
     *
     * @param completedTime the value for story.completedTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompletedTime(Date completedTime) {
        this.completedTime = completedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.completed
     *
     * @return the value of story.completed
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getCompleted() {
        return completed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.completed
     *
     * @param completed the value for story.completed
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompleted(Boolean completed) {
        this.completed = completed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.creatorId
     *
     * @return the value of story.creatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.creatorId
     *
     * @param creatorId the value for story.creatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.creatorName
     *
     * @return the value of story.creatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.creatorName
     *
     * @param creatorName the value for story.creatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.description
     *
     * @return the value of story.description
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.description
     *
     * @param description the value for story.description
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.acceptanceLevel
     *
     * @return the value of story.acceptanceLevel
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getAcceptanceLevel() {
        return acceptanceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.acceptanceLevel
     *
     * @param acceptanceLevel the value for story.acceptanceLevel
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setAcceptanceLevel(String acceptanceLevel) {
        this.acceptanceLevel = acceptanceLevel == null ? null : acceptanceLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.priority
     *
     * @return the value of story.priority
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.priority
     *
     * @param priority the value for story.priority
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.parentStoryId
     *
     * @return the value of story.parentStoryId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getParentStoryId() {
        return parentStoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.parentStoryId
     *
     * @param parentStoryId the value for story.parentStoryId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setParentStoryId(Integer parentStoryId) {
        this.parentStoryId = parentStoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.completable
     *
     * @return the value of story.completable
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getCompletable() {
        return completable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.completable
     *
     * @param completable the value for story.completable
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompletable(Boolean completable) {
        this.completable = completable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.creatorAvatar
     *
     * @return the value of story.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getCreatorAvatar() {
        return creatorAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.creatorAvatar
     *
     * @param creatorAvatar the value for story.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreatorAvatar(String creatorAvatar) {
        this.creatorAvatar = creatorAvatar == null ? null : creatorAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table story
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public StoryObject(StoryObject parent) {
        this.id = parent.getId();
        this.projectId = parent.getProjectId();
        this.companyId = parent.getCompanyId();
        this.pre = parent.getPre();
        this.post = parent.getPost();
        this.deleted = parent.getDeleted();
        this.created = parent.getCreated();
        this.updated = parent.getUpdated();
        this.completedTime = parent.getCompletedTime();
        this.completed = parent.getCompleted();
        this.creatorId = parent.getCreatorId();
        this.creatorName = parent.getCreatorName();
        this.description = parent.getDescription();
        this.acceptanceLevel = parent.getAcceptanceLevel();
        this.priority = parent.getPriority();
        this.parentStoryId = parent.getParentStoryId();
        this.completable = parent.getCompletable();
        this.creatorAvatar = parent.getCreatorAvatar();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table story
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public StoryObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table story
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public StoryObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table story
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public StoryObject(boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table story
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public StoryObject(int id, boolean deleted) {
        this.id = id;
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table story
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    @Override
    public StoryObject copy() {
        return new StoryObject(this);
    }
}