/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

public class SubscriberObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber.subscribeId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer subscribeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber.subscribeType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String subscribeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber.id
     *
     * @return the value of subscriber.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber.id
     *
     * @param id the value for subscriber.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber.userId
     *
     * @return the value of subscriber.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber.userId
     *
     * @param userId the value for subscriber.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber.subscribeId
     *
     * @return the value of subscriber.subscribeId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getSubscribeId() {
        return subscribeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber.subscribeId
     *
     * @param subscribeId the value for subscriber.subscribeId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setSubscribeId(Integer subscribeId) {
        this.subscribeId = subscribeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber.subscribeType
     *
     * @return the value of subscriber.subscribeType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getSubscribeType() {
        return subscribeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber.subscribeType
     *
     * @param subscribeType the value for subscriber.subscribeType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setSubscribeType(String subscribeType) {
        this.subscribeType = subscribeType == null ? null : subscribeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber.companyId
     *
     * @return the value of subscriber.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber.companyId
     *
     * @param companyId the value for subscriber.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public SubscriberObject(SubscriberObject parent) {
        this.id = parent.getId();
        this.userId = parent.getUserId();
        this.subscribeId = parent.getSubscribeId();
        this.subscribeType = parent.getSubscribeType();
        this.companyId = parent.getCompanyId();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public SubscriberObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public SubscriberObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    @Override
    public SubscriberObject copy() {
        return new SubscriberObject(this);
    }
}