/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

import java.util.Date;

public class TodoObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.todolistId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer todolistId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.content
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.position
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Double position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.completed
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean completed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.dueDate
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date dueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.creatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.creatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.assigneeId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer assigneeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.updated
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.doing
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean doing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.projectTodoId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer projectTodoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.todoType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String todoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.description
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.estimate
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer estimate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.spendTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer spendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.priority
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.status
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.startTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.completeTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date completeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.completerId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer completerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String creatorAvatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.id
     *
     * @return the value of todo.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.id
     *
     * @param id the value for todo.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.projectId
     *
     * @return the value of todo.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.projectId
     *
     * @param projectId the value for todo.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.todolistId
     *
     * @return the value of todo.todolistId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getTodolistId() {
        return todolistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.todolistId
     *
     * @param todolistId the value for todo.todolistId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setTodolistId(Integer todolistId) {
        this.todolistId = todolistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.content
     *
     * @return the value of todo.content
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.content
     *
     * @param content the value for todo.content
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.position
     *
     * @return the value of todo.position
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Double getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.position
     *
     * @param position the value for todo.position
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setPosition(Double position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.completed
     *
     * @return the value of todo.completed
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getCompleted() {
        return completed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.completed
     *
     * @param completed the value for todo.completed
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompleted(Boolean completed) {
        this.completed = completed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.dueDate
     *
     * @return the value of todo.dueDate
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.dueDate
     *
     * @param dueDate the value for todo.dueDate
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.creatorName
     *
     * @return the value of todo.creatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.creatorName
     *
     * @param creatorName the value for todo.creatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.creatorId
     *
     * @return the value of todo.creatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.creatorId
     *
     * @param creatorId the value for todo.creatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.assigneeId
     *
     * @return the value of todo.assigneeId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getAssigneeId() {
        return assigneeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.assigneeId
     *
     * @param assigneeId the value for todo.assigneeId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setAssigneeId(Integer assigneeId) {
        this.assigneeId = assigneeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.deleted
     *
     * @return the value of todo.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.deleted
     *
     * @param deleted the value for todo.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.created
     *
     * @return the value of todo.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.created
     *
     * @param created the value for todo.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.updated
     *
     * @return the value of todo.updated
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.updated
     *
     * @param updated the value for todo.updated
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.companyId
     *
     * @return the value of todo.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.companyId
     *
     * @param companyId the value for todo.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.doing
     *
     * @return the value of todo.doing
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getDoing() {
        return doing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.doing
     *
     * @param doing the value for todo.doing
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setDoing(Boolean doing) {
        this.doing = doing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.projectTodoId
     *
     * @return the value of todo.projectTodoId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getProjectTodoId() {
        return projectTodoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.projectTodoId
     *
     * @param projectTodoId the value for todo.projectTodoId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setProjectTodoId(Integer projectTodoId) {
        this.projectTodoId = projectTodoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.todoType
     *
     * @return the value of todo.todoType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getTodoType() {
        return todoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.todoType
     *
     * @param todoType the value for todo.todoType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setTodoType(String todoType) {
        this.todoType = todoType == null ? null : todoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.description
     *
     * @return the value of todo.description
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.description
     *
     * @param description the value for todo.description
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.estimate
     *
     * @return the value of todo.estimate
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getEstimate() {
        return estimate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.estimate
     *
     * @param estimate the value for todo.estimate
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setEstimate(Integer estimate) {
        this.estimate = estimate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.spendTime
     *
     * @return the value of todo.spendTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getSpendTime() {
        return spendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.spendTime
     *
     * @param spendTime the value for todo.spendTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setSpendTime(Integer spendTime) {
        this.spendTime = spendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.priority
     *
     * @return the value of todo.priority
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.priority
     *
     * @param priority the value for todo.priority
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.status
     *
     * @return the value of todo.status
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.status
     *
     * @param status the value for todo.status
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.startTime
     *
     * @return the value of todo.startTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.startTime
     *
     * @param startTime the value for todo.startTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.completeTime
     *
     * @return the value of todo.completeTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.completeTime
     *
     * @param completeTime the value for todo.completeTime
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.completerId
     *
     * @return the value of todo.completerId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCompleterId() {
        return completerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.completerId
     *
     * @param completerId the value for todo.completerId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompleterId(Integer completerId) {
        this.completerId = completerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.creatorAvatar
     *
     * @return the value of todo.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getCreatorAvatar() {
        return creatorAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.creatorAvatar
     *
     * @param creatorAvatar the value for todo.creatorAvatar
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreatorAvatar(String creatorAvatar) {
        this.creatorAvatar = creatorAvatar == null ? null : creatorAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public TodoObject(TodoObject parent) {
        this.id = parent.getId();
        this.projectId = parent.getProjectId();
        this.todolistId = parent.getTodolistId();
        this.content = parent.getContent();
        this.position = parent.getPosition();
        this.completed = parent.getCompleted();
        this.dueDate = parent.getDueDate();
        this.creatorName = parent.getCreatorName();
        this.creatorId = parent.getCreatorId();
        this.assigneeId = parent.getAssigneeId();
        this.deleted = parent.getDeleted();
        this.created = parent.getCreated();
        this.updated = parent.getUpdated();
        this.companyId = parent.getCompanyId();
        this.doing = parent.getDoing();
        this.projectTodoId = parent.getProjectTodoId();
        this.todoType = parent.getTodoType();
        this.description = parent.getDescription();
        this.estimate = parent.getEstimate();
        this.spendTime = parent.getSpendTime();
        this.priority = parent.getPriority();
        this.status = parent.getStatus();
        this.startTime = parent.getStartTime();
        this.completeTime = parent.getCompleteTime();
        this.completerId = parent.getCompleterId();
        this.creatorAvatar = parent.getCreatorAvatar();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public TodoObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public TodoObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public TodoObject(boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public TodoObject(int id, boolean deleted) {
        this.id = id;
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    @Override
    public TodoObject copy() {
        return new TodoObject(this);
    }
}