/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

import java.util.Date;

public class TopicObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.title
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.excerpt
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String excerpt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.lastUpdatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer lastUpdatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.lastUpdatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String lastUpdatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.refId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer refId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.refType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private String refType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.updated
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.bcId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer bcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.stick
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Boolean stick;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.projectId
     *
     * @return the value of topic.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.projectId
     *
     * @param projectId the value for topic.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.title
     *
     * @return the value of topic.title
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.title
     *
     * @param title the value for topic.title
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.excerpt
     *
     * @return the value of topic.excerpt
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getExcerpt() {
        return excerpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.excerpt
     *
     * @param excerpt the value for topic.excerpt
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setExcerpt(String excerpt) {
        this.excerpt = excerpt == null ? null : excerpt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.lastUpdatorId
     *
     * @return the value of topic.lastUpdatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getLastUpdatorId() {
        return lastUpdatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.lastUpdatorId
     *
     * @param lastUpdatorId the value for topic.lastUpdatorId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setLastUpdatorId(Integer lastUpdatorId) {
        this.lastUpdatorId = lastUpdatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.lastUpdatorName
     *
     * @return the value of topic.lastUpdatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getLastUpdatorName() {
        return lastUpdatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.lastUpdatorName
     *
     * @param lastUpdatorName the value for topic.lastUpdatorName
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setLastUpdatorName(String lastUpdatorName) {
        this.lastUpdatorName = lastUpdatorName == null ? null : lastUpdatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.refId
     *
     * @return the value of topic.refId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.refId
     *
     * @param refId the value for topic.refId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setRefId(Integer refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.refType
     *
     * @return the value of topic.refType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public String getRefType() {
        return refType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.refType
     *
     * @param refType the value for topic.refType
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setRefType(String refType) {
        this.refType = refType == null ? null : refType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.deleted
     *
     * @return the value of topic.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.deleted
     *
     * @param deleted the value for topic.deleted
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.created
     *
     * @return the value of topic.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.created
     *
     * @param created the value for topic.created
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.updated
     *
     * @return the value of topic.updated
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.updated
     *
     * @param updated the value for topic.updated
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.bcId
     *
     * @return the value of topic.bcId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getBcId() {
        return bcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.bcId
     *
     * @param bcId the value for topic.bcId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setBcId(Integer bcId) {
        this.bcId = bcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.companyId
     *
     * @return the value of topic.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.companyId
     *
     * @param companyId the value for topic.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.stick
     *
     * @return the value of topic.stick
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Boolean getStick() {
        return stick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.stick
     *
     * @param stick the value for topic.stick
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setStick(Boolean stick) {
        this.stick = stick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public TopicObject(TopicObject parent) {
        this.id = parent.getId();
        this.projectId = parent.getProjectId();
        this.title = parent.getTitle();
        this.excerpt = parent.getExcerpt();
        this.lastUpdatorId = parent.getLastUpdatorId();
        this.lastUpdatorName = parent.getLastUpdatorName();
        this.refId = parent.getRefId();
        this.refType = parent.getRefType();
        this.deleted = parent.getDeleted();
        this.created = parent.getCreated();
        this.updated = parent.getUpdated();
        this.bcId = parent.getBcId();
        this.companyId = parent.getCompanyId();
        this.stick = parent.getStick();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public TopicObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public TopicObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public TopicObject(boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public TopicObject(int id, boolean deleted) {
        this.id = id;
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    @Override
    public TopicObject copy() {
        return new TopicObject(this);
    }
}