/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper.model;

import java.util.Date;

public class TrashObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trash.id
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trash.attachType
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    private String attachType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trash.attachId
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    private Integer attachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trash.companyId
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trash.projectId
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trash.deletedTime
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    private Date deletedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trash.id
     *
     * @return the value of trash.id
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trash.id
     *
     * @param id the value for trash.id
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trash.attachType
     *
     * @return the value of trash.attachType
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    public String getAttachType() {
        return attachType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trash.attachType
     *
     * @param attachType the value for trash.attachType
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    public void setAttachType(String attachType) {
        this.attachType = attachType == null ? null : attachType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trash.attachId
     *
     * @return the value of trash.attachId
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    public Integer getAttachId() {
        return attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trash.attachId
     *
     * @param attachId the value for trash.attachId
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    public void setAttachId(Integer attachId) {
        this.attachId = attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trash.companyId
     *
     * @return the value of trash.companyId
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trash.companyId
     *
     * @param companyId the value for trash.companyId
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trash.projectId
     *
     * @return the value of trash.projectId
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trash.projectId
     *
     * @param projectId the value for trash.projectId
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trash.deletedTime
     *
     * @return the value of trash.deletedTime
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    public Date getDeletedTime() {
        return deletedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trash.deletedTime
     *
     * @param deletedTime the value for trash.deletedTime
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    public void setDeletedTime(Date deletedTime) {
        this.deletedTime = deletedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trash
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    public TrashObject(TrashObject parent) {
        this.id = parent.getId();
        this.attachType = parent.getAttachType();
        this.attachId = parent.getAttachId();
        this.companyId = parent.getCompanyId();
        this.projectId = parent.getProjectId();
        this.deletedTime = parent.getDeletedTime();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trash
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    public TrashObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trash
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    public TrashObject(int id) {
        this.id = id;
    }
}