/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper.model;

import com.onboard.domain.mapper.model.common.BaseItem;

public class UserProjectObject implements BaseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_project.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_project.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_project.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_project.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_project.customOrder
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    private Integer customOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_project.id
     *
     * @return the value of user_project.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.id
     *
     * @param id the value for user_project.id
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_project.userId
     *
     * @return the value of user_project.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.userId
     *
     * @param userId the value for user_project.userId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_project.projectId
     *
     * @return the value of user_project.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.projectId
     *
     * @param projectId the value for user_project.projectId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_project.companyId
     *
     * @return the value of user_project.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.companyId
     *
     * @param companyId the value for user_project.companyId
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_project.customOrder
     *
     * @return the value of user_project.customOrder
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public Integer getCustomOrder() {
        return customOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.customOrder
     *
     * @param customOrder the value for user_project.customOrder
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public void setCustomOrder(Integer customOrder) {
        this.customOrder = customOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public UserProjectObject(UserProjectObject parent) {
        this.id = parent.getId();
        this.userId = parent.getUserId();
        this.projectId = parent.getProjectId();
        this.companyId = parent.getCompanyId();
        this.customOrder = parent.getCustomOrder();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public UserProjectObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    public UserProjectObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbggenerated Wed Aug 26 19:51:19 CST 2015
     */
    @Override
    public UserProjectObject copy() {
        return new UserProjectObject(this);
    }
}