/*******************************************************************************
 * Copyright [2015] [Onboard team of SERC, Peking University]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.onboard.domain.mapper;

import com.onboard.domain.mapper.model.TrashExample;
import com.onboard.domain.model.Trash;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrashMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trash
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    int countByExample(TrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trash
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    int deleteByExample(TrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trash
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trash
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    int insert(Trash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trash
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    int insertSelective(Trash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trash
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    List<Trash> selectByExample(TrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trash
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    Trash selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trash
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") Trash record, @Param("example") TrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trash
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    int updateByExample(@Param("record") Trash record, @Param("example") TrashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trash
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    int updateByPrimaryKeySelective(Trash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trash
     *
     * @mbggenerated Sat Jul 11 20:33:30 CST 2015
     */
    int updateByPrimaryKey(Trash record);
}
